//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subsection.ShoelacesAndOutsole
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn.apache.pp114", ConfigurationName="Subsection.ShoelacesAndOutsole.SI_PP114_OUT")]
    public interface SI_PP114_OUT
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Subsection.ShoelacesAndOutsole.SI_PP114_OUTResponse> SI_PP114_OUTAsync(Subsection.ShoelacesAndOutsole.SI_PP114_OUTRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn.apache.pp114")]
    public partial class DT_PP114_REQ
    {
        
        private DT_PP114_REQI_REQUEST i_REQUESTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_PP114_REQI_REQUEST I_REQUEST
        {
            get
            {
                return this.i_REQUESTField;
            }
            set
            {
                this.i_REQUESTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn.apache.pp114")]
    public partial class DT_PP114_REQI_REQUEST
    {
        
        private DT_BASEINFO_REQ hEADERField;
        
        private DT_PP114_REQI_REQUESTBODY bODYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_BASEINFO_REQ HEADER
        {
            get
            {
                return this.hEADERField;
            }
            set
            {
                this.hEADERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_PP114_REQI_REQUESTBODY BODY
        {
            get
            {
                return this.bODYField;
            }
            set
            {
                this.bODYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn.apache.common")]
    public partial class DT_BASEINFO_REQ
    {
        
        private string busIdField;
        
        private string uUIDField;
        
        private string senderField;
        
        private string receiverField;
        
        private string dateField;
        
        private string timeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BusId
        {
            get
            {
                return this.busIdField;
            }
            set
            {
                this.busIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Receiver
        {
            get
            {
                return this.receiverField;
            }
            set
            {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn.apache.pp114")]
    public partial class DT_PP114_RSP
    {
        
        private string iS_SUCCESSField;
        
        private string eRR_MSGField;
        
        private DT_PP114_RSPRES rESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IS_SUCCESS
        {
            get
            {
                return this.iS_SUCCESSField;
            }
            set
            {
                this.iS_SUCCESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ERR_MSG
        {
            get
            {
                return this.eRR_MSGField;
            }
            set
            {
                this.eRR_MSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DT_PP114_RSPRES RES
        {
            get
            {
                return this.rESField;
            }
            set
            {
                this.rESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn.apache.pp114")]
    public partial class DT_PP114_RSPRES
    {
        
        private string tOTALField;
        
        private DT_PP114_RSPRESDATAS[] dATASField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TOTAL
        {
            get
            {
                return this.tOTALField;
            }
            set
            {
                this.tOTALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DATAS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_PP114_RSPRESDATAS[] DATAS
        {
            get
            {
                return this.dATASField;
            }
            set
            {
                this.dATASField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn.apache.pp114")]
    public partial class DT_PP114_RSPRESDATAS
    {
        
        private string art_noField;
        
        private string workshop_sectionField;
        
        private string start_codeField;
        
        private string end_codeField;
        
        private string item_noField;
        
        private string item_nameField;
        
        private string effective_dateField;
        
        private string expiration_dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string art_no
        {
            get
            {
                return this.art_noField;
            }
            set
            {
                this.art_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string workshop_section
        {
            get
            {
                return this.workshop_sectionField;
            }
            set
            {
                this.workshop_sectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string start_code
        {
            get
            {
                return this.start_codeField;
            }
            set
            {
                this.start_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string end_code
        {
            get
            {
                return this.end_codeField;
            }
            set
            {
                this.end_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string item_no
        {
            get
            {
                return this.item_noField;
            }
            set
            {
                this.item_noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string item_name
        {
            get
            {
                return this.item_nameField;
            }
            set
            {
                this.item_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string effective_date
        {
            get
            {
                return this.effective_dateField;
            }
            set
            {
                this.effective_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string expiration_date
        {
            get
            {
                return this.expiration_dateField;
            }
            set
            {
                this.expiration_dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn.apache.pp114")]
    public partial class DT_PP114_REQI_REQUESTBODY
    {
        
        private string poField;
        
        private string tabField;
        
        private string lANGUField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PO
        {
            get
            {
                return this.poField;
            }
            set
            {
                this.poField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tab
        {
            get
            {
                return this.tabField;
            }
            set
            {
                this.tabField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LANGU
        {
            get
            {
                return this.lANGUField;
            }
            set
            {
                this.lANGUField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_PP114_OUTRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn.apache.pp114", Order=0)]
        public Subsection.ShoelacesAndOutsole.DT_PP114_REQ MT_PP114_REQ;
        
        public SI_PP114_OUTRequest()
        {
        }
        
        public SI_PP114_OUTRequest(Subsection.ShoelacesAndOutsole.DT_PP114_REQ MT_PP114_REQ)
        {
            this.MT_PP114_REQ = MT_PP114_REQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_PP114_OUTResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn.apache.pp114", Order=0)]
        public Subsection.ShoelacesAndOutsole.DT_PP114_RSP MT_PP114_RSP;
        
        public SI_PP114_OUTResponse()
        {
        }
        
        public SI_PP114_OUTResponse(Subsection.ShoelacesAndOutsole.DT_PP114_RSP MT_PP114_RSP)
        {
            this.MT_PP114_RSP = MT_PP114_RSP;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface SI_PP114_OUTChannel : Subsection.ShoelacesAndOutsole.SI_PP114_OUT, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class SI_PP114_OUTClient : System.ServiceModel.ClientBase<Subsection.ShoelacesAndOutsole.SI_PP114_OUT>, Subsection.ShoelacesAndOutsole.SI_PP114_OUT
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SI_PP114_OUTClient(EndpointConfiguration endpointConfiguration) : 
                base(SI_PP114_OUTClient.GetBindingForEndpoint(endpointConfiguration), SI_PP114_OUTClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_PP114_OUTClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SI_PP114_OUTClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_PP114_OUTClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SI_PP114_OUTClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_PP114_OUTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Subsection.ShoelacesAndOutsole.SI_PP114_OUTResponse> Subsection.ShoelacesAndOutsole.SI_PP114_OUT.SI_PP114_OUTAsync(Subsection.ShoelacesAndOutsole.SI_PP114_OUTRequest request)
        {
            return base.Channel.SI_PP114_OUTAsync(request);
        }
        
        public System.Threading.Tasks.Task<Subsection.ShoelacesAndOutsole.SI_PP114_OUTResponse> SI_PP114_OUTAsync(Subsection.ShoelacesAndOutsole.DT_PP114_REQ MT_PP114_REQ)
        {
            Subsection.ShoelacesAndOutsole.SI_PP114_OUTRequest inValue = new Subsection.ShoelacesAndOutsole.SI_PP114_OUTRequest();
            inValue.MT_PP114_REQ = MT_PP114_REQ;
            return ((Subsection.ShoelacesAndOutsole.SI_PP114_OUT)(this)).SI_PP114_OUTAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://acqy-poappqas:50000/XISOAPAdapter/MessageServlet?senderParty=&senderServic" +
                        "e=BC_AEQS&receiverParty=&receiverService=&interface=SI_PP114_OUT&interfaceNamesp" +
                        "ace=urn.apache.pp114");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://acqy-poappqas:50001/XISOAPAdapter/MessageServlet?senderParty=&senderServi" +
                        "ce=BC_AEQS&receiverParty=&receiverService=&interface=SI_PP114_OUT&interfaceNames" +
                        "pace=urn.apache.pp114");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }
    }
}
