//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintenanceShoeMaterial
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn.apache.sd105", ConfigurationName="MaintenanceShoeMaterial.SI_SD105_OUT")]
    public interface SI_SD105_OUT
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MaintenanceShoeMaterial.SI_SD105_OUTResponse> SI_SD105_OUTAsync(MaintenanceShoeMaterial.SI_SD105_OUTRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn.apache.sd105")]
    public partial class DT_SD105_REQ
    {
        
        private DT_SD105_REQI_REQUEST i_REQUESTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_SD105_REQI_REQUEST I_REQUEST
        {
            get
            {
                return this.i_REQUESTField;
            }
            set
            {
                this.i_REQUESTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn.apache.sd105")]
    public partial class DT_SD105_REQI_REQUEST
    {
        
        private DT_BASEINFO_REQ hEADERField;
        
        private DT_SD105_REQI_REQUESTBODY[] bODYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_BASEINFO_REQ HEADER
        {
            get
            {
                return this.hEADERField;
            }
            set
            {
                this.hEADERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BODY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_SD105_REQI_REQUESTBODY[] BODY
        {
            get
            {
                return this.bODYField;
            }
            set
            {
                this.bODYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn.apache.common")]
    public partial class DT_BASEINFO_REQ
    {
        
        private string busIdField;
        
        private string uUIDField;
        
        private string senderField;
        
        private string receiverField;
        
        private string dateField;
        
        private string timeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BusId
        {
            get
            {
                return this.busIdField;
            }
            set
            {
                this.busIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Receiver
        {
            get
            {
                return this.receiverField;
            }
            set
            {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn.apache.common")]
    public partial class DT_BASEINFO_RSP
    {
        
        private string busIdField;
        
        private string uUIDField;
        
        private string senderField;
        
        private string receiverField;
        
        private string dateField;
        
        private string timeField;
        
        private string flagField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BusId
        {
            get
            {
                return this.busIdField;
            }
            set
            {
                this.busIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string UUID
        {
            get
            {
                return this.uUIDField;
            }
            set
            {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Receiver
        {
            get
            {
                return this.receiverField;
            }
            set
            {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Flag
        {
            get
            {
                return this.flagField;
            }
            set
            {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn.apache.sd105")]
    public partial class DT_SD105_RSP
    {
        
        private DT_SD105_RSPE_RESPONSE e_RESPONSEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_SD105_RSPE_RESPONSE E_RESPONSE
        {
            get
            {
                return this.e_RESPONSEField;
            }
            set
            {
                this.e_RESPONSEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn.apache.sd105")]
    public partial class DT_SD105_RSPE_RESPONSE
    {
        
        private DT_BASEINFO_RSP hEADERField;
        
        private DT_SD105_RSPE_RESPONSEBODY[] bODYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_BASEINFO_RSP HEADER
        {
            get
            {
                return this.hEADERField;
            }
            set
            {
                this.hEADERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BODY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_SD105_RSPE_RESPONSEBODY[] BODY
        {
            get
            {
                return this.bODYField;
            }
            set
            {
                this.bODYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn.apache.sd105")]
    public partial class DT_SD105_RSPE_RESPONSEBODY
    {
        
        private string mATNRField;
        
        private string mAKTXField;
        
        private string zCOL1_NMField;
        
        private string zCOL2_NMField;
        
        private string zCOL3Field;
        
        private string zCOL4_NMField;
        
        private string zCOL5_NMField;
        
        private string zCOL6Field;
        
        private string eRNAMField;
        
        private string eRSDAField;
        
        private string aENAMField;
        
        private string lAEDAField;
        
        private string lAST_CHANGED_TIMEField;
        
        private string iCONNAME_BEField;
        
        private string iCONNAME_KField;
        
        private string iCONNAME_BField;
        
        private string iCONNAME_YField;
        
        private string rETURNField;
        
        private string mESGField;
        
        private DT_SD105_RSPE_RESPONSEBODYITEM[] iTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATNR
        {
            get
            {
                return this.mATNRField;
            }
            set
            {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MAKTX
        {
            get
            {
                return this.mAKTXField;
            }
            set
            {
                this.mAKTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZCOL1_NM
        {
            get
            {
                return this.zCOL1_NMField;
            }
            set
            {
                this.zCOL1_NMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZCOL2_NM
        {
            get
            {
                return this.zCOL2_NMField;
            }
            set
            {
                this.zCOL2_NMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZCOL3
        {
            get
            {
                return this.zCOL3Field;
            }
            set
            {
                this.zCOL3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZCOL4_NM
        {
            get
            {
                return this.zCOL4_NMField;
            }
            set
            {
                this.zCOL4_NMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ZCOL5_NM
        {
            get
            {
                return this.zCOL5_NMField;
            }
            set
            {
                this.zCOL5_NMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ZCOL6
        {
            get
            {
                return this.zCOL6Field;
            }
            set
            {
                this.zCOL6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ERNAM
        {
            get
            {
                return this.eRNAMField;
            }
            set
            {
                this.eRNAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ERSDA
        {
            get
            {
                return this.eRSDAField;
            }
            set
            {
                this.eRSDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string AENAM
        {
            get
            {
                return this.aENAMField;
            }
            set
            {
                this.aENAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string LAEDA
        {
            get
            {
                return this.lAEDAField;
            }
            set
            {
                this.lAEDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string LAST_CHANGED_TIME
        {
            get
            {
                return this.lAST_CHANGED_TIMEField;
            }
            set
            {
                this.lAST_CHANGED_TIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ICONNAME_BE
        {
            get
            {
                return this.iCONNAME_BEField;
            }
            set
            {
                this.iCONNAME_BEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ICONNAME_K
        {
            get
            {
                return this.iCONNAME_KField;
            }
            set
            {
                this.iCONNAME_KField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string ICONNAME_B
        {
            get
            {
                return this.iCONNAME_BField;
            }
            set
            {
                this.iCONNAME_BField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string ICONNAME_Y
        {
            get
            {
                return this.iCONNAME_YField;
            }
            set
            {
                this.iCONNAME_YField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string RETURN
        {
            get
            {
                return this.rETURNField;
            }
            set
            {
                this.rETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string MESG
        {
            get
            {
                return this.mESGField;
            }
            set
            {
                this.mESGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public DT_SD105_RSPE_RESPONSEBODYITEM[] ITEM
        {
            get
            {
                return this.iTEMField;
            }
            set
            {
                this.iTEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn.apache.sd105")]
    public partial class DT_SD105_RSPE_RESPONSEBODYITEM
    {
        
        private string zJJField;
        
        private string mAKTXField;
        
        private string zARTField;
        
        private string mIIDSField;
        
        private string sUM_TOTALField;
        
        private string sUM_TOTAL_CHECKField;
        
        private string loField;
        
        private string upload_dateField;
        
        private string date_Change_dateField;
        
        private string zKFFZR_NMField;
        
        private string zBM_XField;
        
        private string zSTATUS_NMField;
        
        private string zCOL1_NMField;
        
        private string zCOL2_NMField;
        
        private string zCOL3_NMField;
        
        private string zCOL4_NMField;
        
        private string zCOL5_NMField;
        
        private string zCOL6_NMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZJJ
        {
            get
            {
                return this.zJJField;
            }
            set
            {
                this.zJJField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MAKTX
        {
            get
            {
                return this.mAKTXField;
            }
            set
            {
                this.mAKTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZART
        {
            get
            {
                return this.zARTField;
            }
            set
            {
                this.zARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MIIDS
        {
            get
            {
                return this.mIIDSField;
            }
            set
            {
                this.mIIDSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SUM_TOTAL
        {
            get
            {
                return this.sUM_TOTALField;
            }
            set
            {
                this.sUM_TOTALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SUM_TOTAL_CHECK
        {
            get
            {
                return this.sUM_TOTAL_CHECKField;
            }
            set
            {
                this.sUM_TOTAL_CHECKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string LO
        {
            get
            {
                return this.loField;
            }
            set
            {
                this.loField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Upload_date
        {
            get
            {
                return this.upload_dateField;
            }
            set
            {
                this.upload_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Date_Change_date
        {
            get
            {
                return this.date_Change_dateField;
            }
            set
            {
                this.date_Change_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ZKFFZR_NM
        {
            get
            {
                return this.zKFFZR_NMField;
            }
            set
            {
                this.zKFFZR_NMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ZBM_X
        {
            get
            {
                return this.zBM_XField;
            }
            set
            {
                this.zBM_XField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ZSTATUS_NM
        {
            get
            {
                return this.zSTATUS_NMField;
            }
            set
            {
                this.zSTATUS_NMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ZCOL1_NM
        {
            get
            {
                return this.zCOL1_NMField;
            }
            set
            {
                this.zCOL1_NMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ZCOL2_NM
        {
            get
            {
                return this.zCOL2_NMField;
            }
            set
            {
                this.zCOL2_NMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ZCOL3_NM
        {
            get
            {
                return this.zCOL3_NMField;
            }
            set
            {
                this.zCOL3_NMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string ZCOL4_NM
        {
            get
            {
                return this.zCOL4_NMField;
            }
            set
            {
                this.zCOL4_NMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string ZCOL5_NM
        {
            get
            {
                return this.zCOL5_NMField;
            }
            set
            {
                this.zCOL5_NMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string ZCOL6_NM
        {
            get
            {
                return this.zCOL6_NMField;
            }
            set
            {
                this.zCOL6_NMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn.apache.sd105")]
    public partial class DT_SD105_REQI_REQUESTBODY
    {
        
        private string mATNRField;
        
        private string lANGUField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATNR
        {
            get
            {
                return this.mATNRField;
            }
            set
            {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LANGU
        {
            get
            {
                return this.lANGUField;
            }
            set
            {
                this.lANGUField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_SD105_OUTRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn.apache.sd105", Order=0)]
        public MaintenanceShoeMaterial.DT_SD105_REQ MT_SD105_REQ;
        
        public SI_SD105_OUTRequest()
        {
        }
        
        public SI_SD105_OUTRequest(MaintenanceShoeMaterial.DT_SD105_REQ MT_SD105_REQ)
        {
            this.MT_SD105_REQ = MT_SD105_REQ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_SD105_OUTResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn.apache.sd105", Order=0)]
        public MaintenanceShoeMaterial.DT_SD105_RSP MT_SD105_RSP;
        
        public SI_SD105_OUTResponse()
        {
        }
        
        public SI_SD105_OUTResponse(MaintenanceShoeMaterial.DT_SD105_RSP MT_SD105_RSP)
        {
            this.MT_SD105_RSP = MT_SD105_RSP;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface SI_SD105_OUTChannel : MaintenanceShoeMaterial.SI_SD105_OUT, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class SI_SD105_OUTClient : System.ServiceModel.ClientBase<MaintenanceShoeMaterial.SI_SD105_OUT>, MaintenanceShoeMaterial.SI_SD105_OUT
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SI_SD105_OUTClient(EndpointConfiguration endpointConfiguration) : 
                base(SI_SD105_OUTClient.GetBindingForEndpoint(endpointConfiguration), SI_SD105_OUTClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_SD105_OUTClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SI_SD105_OUTClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_SD105_OUTClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SI_SD105_OUTClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_SD105_OUTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MaintenanceShoeMaterial.SI_SD105_OUTResponse> MaintenanceShoeMaterial.SI_SD105_OUT.SI_SD105_OUTAsync(MaintenanceShoeMaterial.SI_SD105_OUTRequest request)
        {
            return base.Channel.SI_SD105_OUTAsync(request);
        }
        
        public System.Threading.Tasks.Task<MaintenanceShoeMaterial.SI_SD105_OUTResponse> SI_SD105_OUTAsync(MaintenanceShoeMaterial.DT_SD105_REQ MT_SD105_REQ)
        {
            MaintenanceShoeMaterial.SI_SD105_OUTRequest inValue = new MaintenanceShoeMaterial.SI_SD105_OUTRequest();
            inValue.MT_SD105_REQ = MT_SD105_REQ;
            return ((MaintenanceShoeMaterial.SI_SD105_OUT)(this)).SI_SD105_OUTAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://acqy-poappqas:50000/XISOAPAdapter/MessageServlet?senderParty=&senderServic" +
                        "e=BC_AEQS&receiverParty=&receiverService=&interface=SI_SD105_OUT&interfaceNamesp" +
                        "ace=urn.apache.sd105");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://acqy-poappqas:50001/XISOAPAdapter/MessageServlet?senderParty=&senderServi" +
                        "ce=BC_AEQS&receiverParty=&receiverService=&interface=SI_SD105_OUT&interfaceNames" +
                        "pace=urn.apache.sd105");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }
    }
}
